spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 7654321
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/flowable?cuseUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8